from . import commands
from . import start
from . import bekor_qil
from . import ortga_menu
from . import ism_tahrirlash
from . import aboutme
from . import boglangan_kanal
from . import sozlamalar
from . import admingamurojaat
from . import test_tuzish
from . import oddiy_test
from . import oddiy_test_qulda
from . import oddiy_test_avto
from . import blok_test
from . import blok_test_qulda
from . import blok_test_avto
from . import add_javob_blok
from . import add_javob_oddiy
from . import add_javob
from . import mytests
from . import tekshirish
from . import botdan_foydalanish
from . import testni_yakunlash
from . import natija_kurish
from . import post_joylansin
from . import pastdagi_tugma
from . import inline_keyboard_remover
from . import notstate