from . import inline_ha_yoq
from . import test_egasiga
from . import avto_qulda
from . import soatlar
from . import minutlar
from . import tushunarli
from . import info
from . import botgautish
from . import qayta
from . import javob_yuborishni_boshlash
from . import post_joyla